In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import joblib
import os

In [2]:
df = pd.read_csv('../DataSet/cleaned_job_data.csv')
df

,Job_Title,Industry,Job_Status,AI_Impact_Level,Median_Salary_(USD),Required_Education,Experience_Required_(Years),Job_Openings_(2024),Projected_Openings_(2030),Remote_Work_Ratio,Automation_Risk,Location,Gender_Diversity,Growth_Rate,Risk_Category,Seniority,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030
0,software engineer,Healthcare,Decreasing,High,102875.23,PhD,5,6308,1454,36.35,1.74,Germany,23.51,-0.769499,Low,Regular,0.39,0.68,0.60
1,software engineer,Healthcare,Decreasing,High,102875.23,PhD,5,6308,1454,36.35,1.74,Germany,23.51,-0.769499,Low,Regular,0.16,0.57,0.56
2,software engineer,Healthcare,Decreasing,High,102875.23,PhD,5,6308,1454,36.35,1.74,Germany,23.51,-0.769499,Low,Regular,0.61,0.67,0.70
3,software engineer,Healthcare,Decreasing,High,102875.23,PhD,5,6308,1454,36.35,1.74,Germany,23.51,-0.769499,Low,Regular,0.32,0.52,0.36
4,software engineer,Healthcare,Decreasing,High,102875.23,PhD,5,6308,1454,36.35,1.74,Germany,23.51,-0.769499,Low,Regular,0.06,1.17,0.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28624,software engineer,Finance,Decreasing,Moderate,45199.51,Bachelor’s Degree,3,3142,278,2.09,70.09,Canada,70.89,-0.911521,High,Regular,0.68,1.12,0.34
28625,software engineer,Finance,Decreasing,Moderate,45199.51,Bachelor’s Degree,3,3142,278,2.09,70.09,Canada,70.89,-0.911521,High,Regular,0.21,0.60,0.41
28626,software engineer,Finance,Decreasing,Moderate,45199.51,Bachelor’s Degree,3,3142,278,2.09,70.09,Canada,70.89,-0.911521,High,Regular,0.64,0.63,0.31
28627,software engineer,Finance,Decreasing,Moderate,45199.51,Bachelor’s Degree,3,3142,278,2.09,70.09,Canada,70.89,-0.911521,High,Regular,0.06,1.16,0.61
28628,software engineer,Finance,Decreasing,Moderate,45199.51,Bachelor’s Degree,3,3142,278,2.09,70.09,Canada,70.89,-0.911521,High,Regular,0.89,0.83,0.55

In [3]:
df['Location'].value_counts()

Location
Brazil       4785
UK           3979
Canada       3885
India        3654
Germany      3273
USA          3186
Australia    3016
China        2851
Name: count, dtype: int64

## Label Encoding for categorical columns

In [4]:

df = pd.read_csv('../DataSet/cleaned_job_data.csv')

categorical_cols = [
    'Job_Title', 'Industry', 'Job_Status', 'Required_Education', 
    'Location', 'Risk_Category', 'Seniority', 'AI_Impact_Level'
]

encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

joblib.dump(encoders, '../DataSet/Encoder/label_encoders.pkl')
df.head()

,Job_Title,Industry,Job_Status,AI_Impact_Level,Median_Salary_(USD),Required_Education,Experience_Required_(Years),Job_Openings_(2024),Projected_Openings_(2030),Remote_Work_Ratio,Automation_Risk,Location,Gender_Diversity,Growth_Rate,Risk_Category,Seniority,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030
0,3,3,0,0,102875.23,4,5,6308,1454,36.35,1.74,4,23.51,-0.769499,1,0,0.39,0.68,0.60
1,3,3,0,0,102875.23,4,5,6308,1454,36.35,1.74,4,23.51,-0.769499,1,0,0.16,0.57,0.56
2,3,3,0,0,102875.23,4,5,6308,1454,36.35,1.74,4,23.51,-0.769499,1,0,0.61,0.67,0.70
3,3,3,0,0,102875.23,4,5,6308,1454,36.35,1.74,4,23.51,-0.769499,1,0,0.32,0.52,0.36
4,3,3,0,0,102875.23,4,5,6308,1454,36.35,1.74,4,23.51,-0.769499,1,0,0.06,1.17,0.53

## Use StandardScaler to fit large numbers like Median_Salary_(USD) for ML model for higher predictions

In [5]:
import joblib

numerical_cols = [
    'Median_Salary_(USD)', 'Experience_Required_(Years)', 'Job_Openings_(2024)',
    'Projected_Openings_(2030)', 'Remote_Work_Ratio', 'Automation_Risk',
    'Gender_Diversity', 'Growth_Rate', 'AI_Exposure_Index', 
    'Tech_Growth_Factor', 'Automation_Probability_2030'
]

scaler = StandardScaler()

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

joblib.dump(scaler, '../DataSet/Scaler/scaler.pkl')
df

,Job_Title,Industry,Job_Status,AI_Impact_Level,Median_Salary_(USD),Required_Education,Experience_Required_(Years),Job_Openings_(2024),Projected_Openings_(2030),Remote_Work_Ratio,Automation_Risk,Location,Gender_Diversity,Growth_Rate,Risk_Category,Seniority,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030
0,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,-0.438781,-1.071137,0.829182
1,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,-1.244947,-1.454739,0.479884
2,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,0.332335,-1.106010,1.702427
3,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,-0.684136,-1.629104,-1.266606
4,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,-1.595454,0.637635,0.217910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28624,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,0.577690,0.463270,-1.441255
28625,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,-1.069694,-1.350121,-0.829984
28626,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,0.437487,-1.245502,-1.703229
28627,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,-1.595454,0.602762,0.916506
28628,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,1.313755,-0.548044,0.392559

In [6]:
is_high_encoded_val = encoders['AI_Impact_Level'].transform(['High'])[0]

df['Is_High_Risk'] = (df['AI_Impact_Level'] == is_high_encoded_val).astype(int)

print("Feature Engineering complete. Target column is now 'Is_High_Risk'.")
print("High Risk Jobs:", df['Is_High_Risk'].sum())
print("Total Jobs:", len(df))

Feature Engineering complete. Target column is now 'Is_High_Risk'.
High Risk Jobs: 9691
Total Jobs: 28629

In [7]:
df

,Job_Title,Industry,Job_Status,AI_Impact_Level,Median_Salary_(USD),Required_Education,Experience_Required_(Years),Job_Openings_(2024),Projected_Openings_(2030),Remote_Work_Ratio,Automation_Risk,Location,Gender_Diversity,Growth_Rate,Risk_Category,Seniority,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Is_High_Risk
0,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,-0.438781,-1.071137,0.829182,1
1,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,-1.244947,-1.454739,0.479884,1
2,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,0.332335,-1.106010,1.702427,1
3,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,-0.684136,-1.629104,-1.266606,1
4,3,3,0,0,0.397944,4,-0.846500,0.484342,-1.203914,-0.495603,-1.479939,4,-1.510780,-0.344427,1,0,-1.595454,0.637635,0.217910,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28624,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,0.577690,0.463270,-1.441255,0
28625,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,-1.069694,-1.350121,-0.829984,0
28626,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,0.437487,-1.245502,-1.703229,0
28627,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,-1.595454,0.602762,0.916506,0
28628,3,2,0,2,-1.344789,1,-1.182108,-0.615865,-1.608389,-1.704488,0.849130,2,1.191724,-0.362334,0,0,1.313755,-0.548044,0.392559,0

In [8]:
df.to_csv('../DataSet/ml_ready_data.csv', index=False)

print("Data successfully saved to DataSet/ml_ready_data.csv!")

Data successfully saved to DataSet/ml_ready_data.csv!